### ISSUE TITLE
Is feedback alignment code working?

### ISSUE THREAD

**Issue by mattroos** [willwx/sign-symmetry#1]
@willwx Did you get the FA code in this repo to work? I'd like to try it, but don't want to jump into six year old code that may have never actually worked. Hoping you completed it and it is/was functional!

**Comment by willwx** [comment]
Hi @mattroos, the code worked in 2019. It should still work, but due to the hacky implementation (using PyTorch's private `torch._thnn`, long deprecated), this code requires [torch <= 1.2.0](https://pytorch.org/get-started/previous-versions/), which in turn requires older GPUs (e.g., works on GTX 20xx but not on 30xx).
